### ISSUE TITLE
setState的问题

### ISSUE THREAD

**Issue by PolarChill** [MrWindlike/React-Source-Reading#1]
setState不应该应该依靠他们的值来计算下一个状态, 而应该这样写

` this.setState((prevState, props) => ({
      count: prevState.count + 1
    }));`
 示例那样写法是不是不太好?  小白,还请指教

**Comment by MrWindlike** [comment]
是的，如果像示例那样写的话在同一个函数里多次调用`setState`，不熟悉`setState`的异步机制的话可能会导致某些BUG，所以`this.setState((prevState, props) => ({ count: prevState.count + 1 }));`这样写会比较好，示例里只是展示一些下`setState`的异步机制。
